auth0:
  audience: https://travelxapisuk.azurewebsites.net
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://apps.uk.auth0.com/
  datasource:
    username: travelxadmin
    password: SkyFriends1
    url: jdbc:sqlserver://travelxsqlserver.database.windows.net:1433;database=travelxdb;user=travelxadmin@travelxsqlserver;password=SkyFriends1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG